# The URL the site will be built for
base_url = "https://sameerjainhep.github.io/"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = false

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

[markdown]
# Whether to do syntax highlighting
highlight_code = true
highlight_theme = "base16-ocean-dark"  # Choose any Zola-supported theme

[extra]
# Put all your custom variables here

[extra.menu]
# Define the menu items that will appear in the navigation bar
[[extra.menu]]
name = "Home"
url = "/"
weight = 1

[[extra.menu]]
name = "Research"
url = "/research/"
weight = 2

[[extra.menu]]
name = "Blogs"
url = "/blogs/"
weight = 3

[[extra.menu]]
name = "Resources"
url = "/resources/"
weight = 4

[[extra.menu]]
name = "Inspire"
url = "/inspire/"
weight = 5
